### ISSUE TITLE
Frame Preprocessing Step (for flickering)

### ISSUE THREAD

**Issue by djl11** [NVlabs/GA3C#10]
I've just finished reading the GA3C paper, and I didn't notice any mention of the frame processing to remove flickering artifacts, as explained in DeepMind's original Deep-Q paper methods section, and referenced in the experimental setup for the A3C paper.

I've just had a look through the source code, and it seems as though the the Environment._preprocess(image) function is applied on a frame by frame basis, with no joint thresholding across the previous frame. I was wondering if this was a design decision? If not, is there any plan to incorporate this preprocessing step into the model, to more closely resemble DeepMind's A3C approach?

Alternatively, if I've misinterpretted the code (which is entirely possible), I would be grateful if you could point out where/how this preprocessing step is incorporated.

I will try implementing it efficiently myself in the meantime, which you are welcome to use if helpful.

P.s. this code is proving to be extremely useful!
Thanks a lot for sharing!

Dan

**Comment by mbz** [comment]
@djl11 your observation is correct. OpenAI gym is the right place for handling this issue and there are already open [issues](https://github.com/openai/gym/issues/378) about flickering. Implementing this inside GA3C would be a little bit tricky since the code is receiving a single frame every ~4 frames which should be used for prediction.

**Comment by djl11** [comment]
Ok sure, makes sense. Thank you very much for the help!
