### ISSUE TITLE
Why the RPPS, PPS, TPS are consistently increasing

### ISSUE THREAD

**Issue by YukeWang96** [NVlabs/GA3C#46]
Hi,

From running the experiment, I found that the displayed value of `RPPS, PPS, TPS` is consistently increasing for many episodes. How could I know for one configuration speedup over another configuration in a small number of episodes?

Thanks!

**Comment by ifrosio** [comment]
The values are increasing at the beginning because the automatic scheduling mechanism looks for the best configuration. They should stabilize after a while. Since every game is different, and every machine is different as well, it is hard to define an optimal configuration for any game/machine. If you work always on the same machine, you can try observing the parameters of the configuration after stabilization, and try to set these as initial parameters for the next experiments. Different games may still require slightly different configurations, but convergence may be reached faster.

**Comment by YukeWang96** [comment]
Another observation I notice is that even if I set the `DYNAMIC_SETTINGS=False` the time from the initial episode to the episodes range with stabilized PPS, RPPS is extremely long. For the first hundreds of episodes, I usually observe a continuously increased number of RPPs and PPS. is this normal? or do I miss something. 

Thanks!

**Comment by ifrosio** [comment]
I believe there is some initialization process (e.g. memory allocation, buffer initialization) which is even not under our control that happens at the beginning. As the reported metrics are moving averages, you should see the slowing effect of this initialization for some time in the reported metrics.

I.
